# Generated by Django 2.2 on 2020-04-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_generic_name_en', models.CharField(max_length=50, verbose_name='英文通用名')),
                ('drug_generic_name_cn', models.CharField(max_length=50, verbose_name='中文通用名')),
                ('common_translation', models.CharField(max_length=50, verbose_name='常用译名')),
                ('brand_name_en', models.CharField(max_length=50, verbose_name='英文商品名')),
                ('brand_name_cn', models.CharField(max_length=50, verbose_name='中文商品名')),
                ('NMPA_approved_tag', models.BooleanField(default=True, verbose_name='是否NMPA批准')),
                ('NMPA_approved_biomarker', models.CharField(max_length=50, verbose_name='NMPA批准的标志物，对应诊断分类')),
                ('NMPA_approved_usage', models.CharField(max_length=50, verbose_name='NMPA批准的用途')),
                ('NMPA_approved_category', models.CharField(max_length=50, verbose_name='NMPA批准的诊断分类')),
                ('NMPA_offlabel_usage', models.CharField(max_length=50, verbose_name='NMPA超说明书适应症')),
                ('NMPA_offlabel_category', models.CharField(max_length=50, verbose_name='NMPA超说明书诊断分类')),
                ('NMPA_indication', models.CharField(max_length=50, verbose_name='NMPA适应症')),
                ('FDA_approved_tag', models.BooleanField(default=True, verbose_name='是否FDA批准')),
                ('FDA_approved_biomarker', models.CharField(max_length=50, verbose_name='FDA批准的标志物，对应诊断分类')),
                ('FDA_approved_usage_en', models.CharField(max_length=50, verbose_name='FDA批准的用途-英文')),
                ('FDA_approved_usage_cn', models.CharField(max_length=50, verbose_name='FDA批准的用途-中文')),
                ('FDA_approved_category', models.CharField(max_length=50, verbose_name='FDA批准的诊断分类')),
                ('FDA_offlabel_usage_en', models.CharField(max_length=50, verbose_name='FDA超说明书适应症-英文')),
                ('FDA_offlabel_usage_cn', models.CharField(max_length=50, verbose_name='FDA超说明书适应症-中文')),
                ('FDA_offlabel_category', models.CharField(max_length=50, verbose_name='FDA超说明书诊断分类')),
                ('FDA_indication_en', models.CharField(max_length=50, verbose_name='FDA适应症-英文')),
                ('FDA_indication_cn', models.CharField(max_length=50, verbose_name='FDA适应症-中文')),
                ('synonyms', models.CharField(max_length=50, verbose_name='别名')),
                ('pharmacologic_category_en', models.CharField(max_length=50, verbose_name='药理学类别-英文')),
                ('pharmacologic_category_cn', models.CharField(max_length=50, verbose_name='药理学类别-中文')),
                ('dosage_forms_en', models.CharField(max_length=50, verbose_name='剂型-英文')),
                ('dosage_forms_cn', models.CharField(max_length=50, verbose_name='剂型-中文')),
            ],
            options={
                'verbose_name': '靶向药物信息',
                'verbose_name_plural': '靶向药物信息',
            },
        ),
    ]
