# Generated by Django 2.2 on 2020-04-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancer',
            options={'verbose_name': '肿瘤疾病信息', 'verbose_name_plural': '肿瘤疾病信息'},
        ),
        migrations.AlterModelOptions(
            name='civic',
            options={'verbose_name': 'Civic数据库', 'verbose_name_plural': 'Civic数据库'},
        ),
        migrations.AlterModelOptions(
            name='clinicaltrials',
            options={'verbose_name': 'ClinicalTrials数据库', 'verbose_name_plural': 'ClinicalTrials数据库'},
        ),
        migrations.AlterModelOptions(
            name='fusion',
            options={'verbose_name': '融合基因', 'verbose_name_plural': '融合基因'},
        ),
        migrations.AlterModelOptions(
            name='gene',
            options={'verbose_name': 'Gene信息', 'verbose_name_plural': 'Gene信息'},
        ),
        migrations.AlterModelOptions(
            name='hereditary',
            options={'verbose_name': '遗传信息', 'verbose_name_plural': '遗传信息'},
        ),
        migrations.AlterModelOptions(
            name='immunityreport',
            options={'verbose_name': '报告中免疫信息', 'verbose_name_plural': '报告中免疫信息'},
        ),
        migrations.AlterModelOptions(
            name='mutation',
            options={'verbose_name': '突变信息', 'verbose_name_plural': '突变信息'},
        ),
        migrations.AlterModelOptions(
            name='oncokb',
            options={'verbose_name': 'OncoKB数据库', 'verbose_name_plural': 'OncoKB数据库'},
        ),
        migrations.AlterModelOptions(
            name='oncokbmutation',
            options={'verbose_name': 'OncoKB数据库Mutation', 'verbose_name_plural': 'OncoKB数据库Mutation'},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'verbose_name': 'Panel信息', 'verbose_name_plural': 'Panel信息'},
        ),
        migrations.AlterModelOptions(
            name='pharmgkb',
            options={'verbose_name': 'PharmGKB数据库', 'verbose_name_plural': 'PharmGKB数据库'},
        ),
        migrations.AlterModelOptions(
            name='refgeneflat',
            options={'verbose_name': 'RefGene的位置', 'verbose_name_plural': 'RefGene的位置'},
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='chemo_therapy_genes',
            new_name='chemo_therapy_gene',
        ),
        migrations.RenameField(
            model_name='panel',
            old_name='target_therapy_genes',
            new_name='target_therapy_gene',
        ),
    ]
