# Generated by Django 2.2 on 2020-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_targetdrug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_approved_biomarker',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA批准的标志物，对应诊断分类'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_approved_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA批准的诊断分类'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_approved_usage_cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA批准的用途-中文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_approved_usage_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA批准的用途-英文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_indication_cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA适应症-中文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_indication_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA适应症-英文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_offlabel_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA超说明书诊断分类'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_offlabel_usage_cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA超说明书适应症-中文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='FDA_offlabel_usage_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FDA超说明书适应症-英文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='NMPA_approved_biomarker',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMPA批准的标志物，对应诊断分类'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='NMPA_approved_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMPA批准的诊断分类'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='NMPA_approved_usage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMPA批准的用途'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='NMPA_indication',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMPA适应症'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='NMPA_offlabel_category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMPA超说明书诊断分类'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='NMPA_offlabel_usage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NMPA超说明书适应症'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='brand_name_cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='中文商品名'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='brand_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='英文商品名'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='common_translation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='常用译名'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='dosage_forms_cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='剂型-中文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='dosage_forms_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='剂型-英文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='drug_generic_name_cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='中文通用名'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='drug_generic_name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='英文通用名'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='pharmacologic_category_cn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='药理学类别-中文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='pharmacologic_category_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='药理学类别-英文'),
        ),
        migrations.AlterField(
            model_name='targetdrug',
            name='synonyms',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='别名'),
        ),
    ]
