# Generated by Django 2.2 on 2020-04-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200409_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancer',
            name='age_choice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='年龄偏好'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='cancer_descritpion',
            field=models.TextField(blank=True, null=True, verbose_name='其它描述'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='cancer_name_cn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='肿瘤中文名'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='cancer_name_en',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='肿瘤英文名'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='category_level_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级分类1级'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='category_level_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级分类2级'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='category_level_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级分类3级'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='category_level_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级分类4级'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='category_level_5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级分类5级'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='category_level_6',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级分类6级'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='gender_choice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='性别偏好'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='heredity_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='遗传模型'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='incidence',
            field=models.FloatField(blank=True, null=True, verbose_name='发病率'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='mortality',
            field=models.FloatField(blank=True, null=True, verbose_name='致死率'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='population_description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='易患病人群'),
        ),
        migrations.AlterField(
            model_name='cancer',
            name='symptom',
            field=models.TextField(blank=True, null=True, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='asco_abstract_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ASCO摘要ID'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='chrom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='染色体'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='chrom2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='染色体2'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='citation',
            field=models.TextField(blank=True, null=True, verbose_name='引用'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='citation_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='引用的ID'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='clinical_significance',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='临床重要性'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='disease',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='肿瘤类型'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='doid',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='doid'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='drug_iteraction_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='药物作用类型'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='drugs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='药物名'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='突变终止位置'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='end2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='突变终止位置2'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='ensembl_version',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='ensembl版本'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='entrez_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Entrez编号'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='evidence_civic_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='civic证据链接'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='evidence_direction',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证据方向'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='evidence_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证据ID'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='evidence_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证据等级'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='evidence_statement',
            field=models.TextField(blank=True, null=True, verbose_name='证据描述'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='evidence_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证据状态'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='evidence_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证据类型'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='gene_civic_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='civic基因链接'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='gene_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因ID'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='last_review',
            field=models.DateField(blank=True, null=True, verbose_name='review日期'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='nct_ids',
            field=models.TextField(blank=True, null=True, verbose_name='nct_ids'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='phenotypes',
            field=models.TextField(blank=True, null=True, verbose_name='表型'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='reference_base',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='参考碱基'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='reference_build',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='reference版本'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='representive_transcript',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENST编号'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='representive_transcript2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ENST编号2'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='source_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='引用的源'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='突变起始位置'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='start2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='突变起始位置2'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='variant',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='突变名称-氨基酸变化'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='variant_base',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='突变碱基'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='variant_civic_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='civic突变链接'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='variant_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='突变ID'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='variant_origin',
            field=models.CharField(blank=True, default='Somatic', max_length=10, null=True, verbose_name='突变来源'),
        ),
        migrations.AlterField(
            model_name='civic',
            name='variant_summary',
            field=models.TextField(blank=True, null=True, verbose_name='突变统计'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='brief_summary',
            field=models.TextField(blank=True, null=True, verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='brief_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='condition',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='适应症'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='intervention_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='干预名称'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='intervention_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='干预类型'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='nct_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NCT编号'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='overall_status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='phase',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='clinicaltrials',
            name='study_first_posted',
            field=models.DateField(blank=True, null=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='host_gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Host基因名'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='partner_gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Partner基因名'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='source',
            field=models.TextField(blank=True, null=True, verbose_name='信息来源'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='chemo_therapy_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否化疗相关'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='driver_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否Driver Gene'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='基因别名'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_description_cn',
            field=models.TextField(blank=True, null=True, verbose_name='基因中文描述'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='基因英文描述'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='genetic_counseling_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否遗传相关'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='immunity_therapy_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否免疫相关'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='lrg_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='LRG编号'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='target_therapy_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否靶向相关'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='transcript_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='转录本ID'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='transcript_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='转录本版本号'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='cancer_type_cn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='肿瘤类型'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='disease_description',
            field=models.TextField(blank=True, null=True, verbose_name='疾病描述'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='evidence',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证据等级'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='hereditary_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='遗传类型'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='omim_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OMIM ID'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='风险等级'),
        ),
        migrations.AlterField(
            model_name='hereditary',
            name='tumor_profiles',
            field=models.TextField(blank=True, null=True, verbose_name='肿瘤profile'),
        ),
        migrations.AlterField(
            model_name='immunityreport',
            name='clinical_guide',
            field=models.TextField(blank=True, null=True, verbose_name='临床指导'),
        ),
        migrations.AlterField(
            model_name='immunityreport',
            name='data_info',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='DataInfo'),
        ),
        migrations.AlterField(
            model_name='immunityreport',
            name='effect',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='作用'),
        ),
        migrations.AlterField(
            model_name='immunityreport',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='immunityreport',
            name='panel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Panel'),
        ),
        migrations.AlterField(
            model_name='immunityreport',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='检测结果'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='BRCA_recheck_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否需要BRCA校正'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='benign_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否良性突变'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='blacklist_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否在黑名单中'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='core_panel_only_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否仅在核心Panel中'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='driver_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否Driver突变'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mnp_benign_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否mnp良性突变'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutation_hgvs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='突变HGVS命名'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mutation_position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='突变位置描述'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='panel_abbr_specific',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='针对的Panle简称'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='whitelist_tag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='是否在白名单中'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='alteration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='突变描述'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='cancer_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='肿瘤类型'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='drug_abstract',
            field=models.TextField(blank=True, null=True, verbose_name='药物描述'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='drug_article_pmid',
            field=models.TextField(blank=True, null=True, verbose_name='药物文章PMID'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='drug_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='药物名称'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='entrez_gene_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Entrez基因ID'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='isoform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ENST编号'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='level',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='protein_change',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='蛋白质变化'),
        ),
        migrations.AlterField(
            model_name='oncokb',
            name='refseq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='转录本编号'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='alteration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='突变描述'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='entrez_gene_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Entrez基因ID'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='isoform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ENST编号'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='mutation_effect',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='突变效应'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='mutation_effect_abstract',
            field=models.TextField(blank=True, null=True, verbose_name='突变效应描述'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='mutation_effect_article_pmid',
            field=models.TextField(blank=True, null=True, verbose_name='突变效应文章PMID'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='oncogenicity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='致癌性'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='protein_change',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='蛋白质变化'),
        ),
        migrations.AlterField(
            model_name='oncokbmutation',
            name='refseq',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='转录本编号'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='chemo_therapy_gene',
            field=models.TextField(blank=True, null=True, verbose_name='化疗基因'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='genetic_counseling_gene',
            field=models.TextField(blank=True, null=True, verbose_name='遗传基因'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='immunity_therapy_gene',
            field=models.TextField(blank=True, null=True, verbose_name='免疫基因'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='mutation_cnv_gene',
            field=models.TextField(blank=True, null=True, verbose_name='CNV基因'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='mutation_fusion_gene',
            field=models.TextField(blank=True, null=True, verbose_name='融合基因'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='mutation_short_gene',
            field=models.TextField(blank=True, null=True, verbose_name='SNP/Indel基因'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='other_gene',
            field=models.TextField(blank=True, null=True, verbose_name='其他基因'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_abbr',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='项目简称'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_abbr_pre',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='项目简称-旧'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Panel分类'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Panel编号'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_library_method',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='建库方法'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_report_index_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Panel在报告封面的名称'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_report_pageheader_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Panel在报告页眉的名称'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_report_type',
            field=models.CharField(blank=True, default='ngs', max_length=10, null=True, verbose_name='Panel的报告类型'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='pharmgkb_sites',
            field=models.TextField(blank=True, null=True, verbose_name='pharmGKB特有位点'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='target_therapy_gene',
            field=models.TextField(blank=True, null=True, verbose_name='靶向基因'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='cds_strand',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='链方向'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='chrom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='染色体'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='clinical_guide',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='临床作用'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='clinical_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='临床类型'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='drug_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='药品名称'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='终止位置'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='evidence_weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='证据等级'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='geno_typ_cn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='基因型中文'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='geno_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='基因型'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='metabolism',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='代谢等级'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='pharmgkb_panel',
            field=models.TextField(blank=True, null=True, verbose_name='pharmGKB Panel'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='rs_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='rs ID'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='side_effect_weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='副作用等级'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='起始位置'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='therapeutic_weight',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='疗效等级'),
        ),
        migrations.AlterField(
            model_name='pharmgkb',
            name='transcript_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='转录本ID'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='cds_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CDS终止位置'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='cds_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CDS起始位置'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='chrom',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='染色体'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='exon_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='外显子个数'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='exon_ends',
            field=models.TextField(blank=True, null=True, verbose_name='各外显子终止位置'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='exon_starts',
            field=models.TextField(blank=True, null=True, verbose_name='各外显子起始位置'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='gene_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='基因名称'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='strand',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='正负链'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='transcript_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='转录本ID'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='tx_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='终止位置'),
        ),
        migrations.AlterField(
            model_name='refgeneflat',
            name='tx_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='起始位置'),
        ),
    ]
