# Generated by Django 2.2 on 2020-04-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200426_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetdrug',
            name='immune_drug_tag',
            field=models.BooleanField(default=False, verbose_name='是否免疫药物'),
        ),
        migrations.AddField(
            model_name='targetdrug',
            name='target_drug_tag',
            field=models.BooleanField(default=True, verbose_name='是否靶向药物'),
        ),
    ]
