# Generated by Django 2.2 on 2020-04-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200409_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='药物名-英文')),
                ('drug_name_cn_official', models.CharField(blank=True, max_length=50, null=True, verbose_name='药物名-中文-官方')),
                ('drug_name_cn_public', models.CharField(blank=True, max_length=50, null=True, verbose_name='药物名-中文-通用')),
                ('drug_name_alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='药物名-别名')),
                ('NMPA_approve_tag', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否NMPA批准')),
                ('FDA_approve_tag', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否FDA批准')),
                ('hormone_tag', models.BooleanField(blank=True, default=False, null=True, verbose_name='是否激素药物')),
                ('target', models.CharField(blank=True, max_length=200, null=True, verbose_name='药物靶点')),
            ],
        ),
    ]
